# Generated by Django 5.2.7 on 2025-10-17 22:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LibraryApp', '0002_course_enrollment_video_delete_book_delete_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='video_url',
        ),
        migrations.AddField(
            model_name='video',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='video_file',
            field=models.FileField(default=django.utils.timezone.now, upload_to='course_videos/'),
            preserve_default=False,
        ),
    ]
